FinanceData/FinanceDataReader: Financial data reader

In [116]:
# FinanceData 설치
# !pip install finance-datareader

In [117]:
# 라이브러리 불러오기
import FinanceDataReader as fdr

In [118]:
# 버전확인
fdr.__version__

'0.9.94'

#### 한국거래소 상장종목 전체 가져오기

In [119]:
dir(fdr)

['DataReader',
 'EtfListing',
 'SnapDataReader',
 'StockListing',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_utils',
 'chart',
 'data',
 'ecos',
 'fred',
 'investing',
 'krx',
 'nasdaq',
 'naver',
 'plot',
 'wikipedia',
 'yahoo']

In [120]:
fdr.StockListing?

Signature: fdr.StockListing(market: str, start=None, end=None) -> pandas.core.frame.DataFrame
Docstring:
read stock list of stock exchanges
* market: 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP',
        'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC',
        'KRX-DELISTING', 'KRX-ADMINISTRATIVE', 'KRX-MARCAP',
        'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE',
        'S&P500',
        'ETF/KR',
File:      d:\kdt_2\anaconda3\lib\site-packages\financedatareader\data.py
Type:      function

In [121]:
stocks = fdr.StockListing('KRX')
stocks_desc = fdr.StockListing('KRX-DESC')

#### 데이터 구조 화인

In [122]:
# 데이터 프레임의 행과 열의 수를 튜플로 반환
stocks.shape, stocks_desc.shape

((2856, 17), (2856, 10))

In [123]:
#행수
stocks.shape[0] , stocks_desc.shape[0]

(2856, 2856)

In [124]:
# 데이터프레임의 처음,마지막 n행 보기, 매개값이 없여면 5행
display(stocks.head(1))
display(stocks_desc.head(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,54100,1,400,0.74,53900,54400,52700,22804926,1228936823600,322965235955000,5969782550,STK

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,3S,KOSDAQ,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시

In [125]:
display(stocks.tail(1))
display(stocks_desc.tail(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
2855,419700,KR7419700000,이브이파킹서비스,KONEX,일반기업부,3,2,-1,-25.0,4,4,2,2675272,7991664,51799998,17266666,KNX

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
2855,238490,힘스,KOSDAQ,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [126]:
# 데이터 프레임에 대한 기본 정보(행수,컴럼명,컬럼수,각 컬럼의 데이터 타입, 결측치 확인)
stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2856 entries, 0 to 2855
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Code         2856 non-null   object
 1   ISU_CD       2856 non-null   object
 2   Name         2856 non-null   object
 3   Market       2856 non-null   object
 4   Dept         2856 non-null   object
 5   Close        2856 non-null   object
 6   ChangeCode   2856 non-null   object
 7   Changes      2856 non-null   int64
 8   ChagesRatio  2856 non-null   float64
 9   Open         2856 non-null   int64
 10  High         2856 non-null   int64
 11  Low          2856 non-null   int64
 12  Volume       2856 non-null   int64
 13  Amount       2856 non-null   int64
 14  Marcap       2856 non-null   int64
 15  Stocks       2856 non-null   int64
 16  MarketId     2856 non-null   object
dtypes: float64(1), int64(8), object(8)
memory usage: 379.4+ KB

In [127]:
# 요약 통계량 제공, 매개값이 없으면 숫자컬럼만 제공함.
# count : nan값을 제외한 컴럼 데이터수
# mean : 평균
# std : 표준편차
# min, max : 최소,최대값
# 사분위수 : 값의 범위를 4분위로 나눈 수. 
stocks.describe()

,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks
count,2856.000000,2856.000000,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03
mean,-252.238095,-1.340434,1.735008e+04,1.772746e+04,1.658957e+04,5.309359e+05,6.083786e+09,8.130226e+11,4.186027e+07
std,3615.763860,3.899823,5.960333e+04,6.369783e+04,5.402176e+04,2.191040e+06,3.565241e+10,7.277021e+12,1.327892e+08
min,-187000.000000,-29.930000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.180000e+07,2.000000e+05
25%,-200.000000,-3.060000,2.000000e+03,2.015000e+03,1.970750e+03,2.497900e+04,1.015650e+08,4.137168e+10,1.017354e+07
50%,-50.000000,-1.280000,4.677500e+03,4.797500e+03,4.445000e+03,9.306500e+04,4.239842e+08,8.954548e+10,1.977295e+07
75%,0.000000,0.000000,1.266750e+04,1.288250e+04,1.211000e+04,2.738850e+05,1.842106e+09,2.277213e+11,4.189457e+07
max,8800.000000,30.000000,2.124000e+06,2.407000e+06,1.736000e+06,3.784488e+07,1.228937e+12,3.229652e+14,5.969783e+09

In [128]:
# 문자열 컬럼(범주형 컬럼)에 대한 요약 통계보기
# count : 컬럼값의 수(nan값제외)
# unique : 컬럼의 고유값 갯수
# top : 최빈값(가장 빈번하게 나타나는 값) or 모든 컬럼 값이 유일한경우 제일 위에 위치한 값
# freq : 최빈값 빈도
stocks.describe(include='O')

          Code        ISU_CD  Name  Market  Dept Close ChangeCode MarketId
count     2856          2856  2856    2856  2856  2856       2856     2856
unique    2856          2856  2856       4    10  1997          6        3
top     005930  KR7005930003  삼성전자  KOSDAQ        2000          2      KSQ
freq         1             1     1    1728   960    11       2013     1776

In [129]:
# 고유값의 목록 확인
print(type(stocks['ChangeCode'].unique()))
print(stocks['ChangeCode'].unique())

<class 'numpy.ndarray'>
['1' '2' '3' '0' '5' '4']

In [130]:
# 고유값의 목록,갯수 확인
print(type(stocks['ChangeCode'].value_counts()))
print(stocks['ChangeCode'].value_counts())

<class 'pandas.core.series.Series'>
ChangeCode
2    2013
1     610
0     126
3      96
5       6
4       5
Name: count, dtype: int64

In [131]:
# 데이터 프레레임의 컬럼 메타정보
stocks.columns

Index(['Code', 'ISU_CD', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode',
       'Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId'],
      dtype='object')

In [132]:
# 컬럼제거 : 필요없는 행이나 열을 제거
new_stocks = stocks.drop('ISU_CD',axis=1)
new_stocks_desc = stocks_desc.drop(['Name', 'Market'],axis=1)
print(new_stocks.columns)
print(new_stocks_desc.columns)

Index(['Code', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode', 'Changes',
       'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount', 'Marcap',
       'Stocks', 'MarketId'],
      dtype='object')
Index(['Code', 'Sector', 'Industry', 'ListingDate', 'SettleMonth',
       'Representative', 'HomePage', 'Region'],
      dtype='object')

#### 2개의 데이터 프레임 합치기
- merge : 가로방향으로 열추가

In [133]:
import pandas as pd

In [134]:
# new_stocks join new_stocks_desc
new_stocks = pd.merge(new_stocks,new_stocks_desc)

In [135]:
new_stocks.shape

(2856, 23)

In [136]:
new_stocks.head(1)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,,54100,1,400,0.74,53900,54400,...,322965235955000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

In [137]:
new_stocks_desc.head(1)

,Code,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시

#### 엑셀로 저장하기

In [138]:
# 엑셀로 저장하기
print(new_stocks.shape)
new_stocks.to_excel('stocks.xlsx',index=False)

(2856, 23)

In [139]:
df = pd.read_excel('stocks.xlsx')

In [140]:
df.shape

(2856, 23)

CSV파일로 저장하기

In [145]:
# CSV파일로 저장하기
new_stocks.to_csv('stocks.csv', index=False)