FinanceData/FinanceDataReader: Financial data reader

In [1]:
# FinanceData 설치
# !pip install finance-datareader

In [22]:
# 라이브러리 불러오기
import FinanceDataReader as fdr

In [23]:
# 버전확인
fdr.__version__

'0.9.94'

#### 한국거래소 상장종목 전체 가져오기

In [24]:
dir(fdr)

['DataReader',
 'EtfListing',
 'SnapDataReader',
 'StockListing',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_utils',
 'chart',
 'data',
 'ecos',
 'fred',
 'investing',
 'krx',
 'nasdaq',
 'naver',
 'plot',
 'wikipedia',
 'yahoo']

In [25]:
fdr.StockListing?

Signature: fdr.StockListing(market: str, start=None, end=None) -> pandas.core.frame.DataFrame
Docstring:
read stock list of stock exchanges
* market: 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP',
        'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC',
        'KRX-DELISTING', 'KRX-ADMINISTRATIVE', 'KRX-MARCAP',
        'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE',
        'S&P500',
        'ETF/KR',
File:      d:\kdt_2\anaconda3\lib\site-packages\financedatareader\data.py
Type:      function

In [26]:
stocks = fdr.StockListing('KRX')
stocks_desc = fdr.StockListing('KRX-DESC')

#### 데이터 구조 화인

In [27]:
# 데이터 프레임의 행과 열의 수를 튜플로 반환
stocks.shape, stocks_desc.shape

((2856, 17), (2856, 10))

In [29]:
#행수
stocks.shape[0] , stocks_desc.shape[0]

(2856, 2856)

In [38]:
# 데이터프레임의 처음,마지막 n행 보기, 매개값이 없여면 5행
display(stocks.head(1))
display(stocks_desc.head(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,54000,1,300,0.56,53900,54400,52700,12919003,694781083200,322368257700000,5969782550,STK

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,3S,KOSDAQ,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시

In [39]:
display(stocks.tail(1))
display(stocks_desc.tail(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
2855,419700,KR7419700000,이브이파킹서비스,KONEX,일반기업부,3,2,-1,-25.0,4,4,3,1975947,6100599,51799998,17266666,KNX

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
2855,238490,힘스,KOSDAQ,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [41]:
# 데이터 프레임에 대한 기본 정보(행수,컴럼명,컬럼수,각 컬럼의 데이터 타입, 결측치 확인)
stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2856 entries, 0 to 2855
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Code         2856 non-null   object
 1   ISU_CD       2856 non-null   object
 2   Name         2856 non-null   object
 3   Market       2856 non-null   object
 4   Dept         2856 non-null   object
 5   Close        2856 non-null   object
 6   ChangeCode   2856 non-null   object
 7   Changes      2856 non-null   int64
 8   ChagesRatio  2856 non-null   float64
 9   Open         2856 non-null   int64
 10  High         2856 non-null   int64
 11  Low          2856 non-null   int64
 12  Volume       2856 non-null   int64
 13  Amount       2856 non-null   int64
 14  Marcap       2856 non-null   int64
 15  Stocks       2856 non-null   int64
 16  MarketId     2856 non-null   object
dtypes: float64(1), int64(8), object(8)
memory usage: 379.4+ KB

In [43]:
# 요약 통계량 제공, 매개값이 없으면 숫자컬럼만 제공함.
# count : nan값을 제외한 컴럼 데이터수
# mean : 평균
# std : 표준편차
# min, max : 최소,최대값
# 사분위수 : 값의 범위를 4분위로 나눈 수. 
stocks.describe()

,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks
count,2856.000000,2856.000000,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03,2.856000e+03
mean,-154.883754,-1.528540,1.732470e+04,1.767110e+04,1.671378e+04,3.537452e+05,3.841891e+09,8.148562e+11,4.186027e+07
std,2738.963062,3.850709,5.959944e+04,6.367565e+04,5.829772e+04,1.488960e+06,2.147610e+10,7.282086e+12,1.327892e+08
min,-16000.000000,-29.930000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.180000e+07,2.000000e+05
25%,-230.000000,-3.180000,2.000000e+03,2.010000e+03,1.969250e+03,1.451250e+04,5.896584e+07,4.111001e+10,1.017354e+07
50%,-65.000000,-1.640000,4.672500e+03,4.765000e+03,4.450000e+03,5.798800e+04,2.766356e+08,8.959150e+10,1.977295e+07
75%,-5.000000,-0.197500,1.264500e+04,1.285500e+04,1.211500e+04,1.759795e+05,1.194099e+09,2.273813e+11,4.189457e+07
max,138000.000000,29.970000,2.124000e+06,2.407000e+06,2.092000e+06,2.820725e+07,6.947811e+11,3.223683e+14,5.969783e+09

In [48]:
# 문자열 컬럼(범주형 컬럼)에 대한 요약 통계보기
# count : 컬럼값의 수(nan값제외)
# unique : 컬럼의 고유값 갯수
# top : 최빈값(가장 빈번하게 나타나는 값) or 모든 컬럼 값이 유일한경우 제일 위에 위치한 값
# freq : 최빈값 빈도
stocks.describe(include='O')

          Code        ISU_CD  Name  Market  Dept Close ChangeCode MarketId
count     2856          2856  2856    2856  2856  2856       2856     2856
unique    2856          2856  2856       4    10  2004          6        3
top     005930  KR7005930003  삼성전자  KOSDAQ        2095          2      KSQ
freq         1             1     1    1728   960     8       2195     1776

In [54]:
# 고유값의 목록 확인
print(type(stocks['ChangeCode'].unique()))
print(stocks['ChangeCode'].unique())

<class 'numpy.ndarray'>
['1' '2' '3' '0' '5' '4']

In [58]:
# 고유값의 목록,갯수 확인
print(type(stocks['ChangeCode'].value_counts()))
print(stocks['ChangeCode'].value_counts())

<class 'pandas.core.series.Series'>
ChangeCode
2    2195
1     454
0     138
3      59
5       7
4       3
Name: count, dtype: int64

In [62]:
# 데이터 프레레임의 컬럼 메타정보
stocks.columns

Index(['Code', 'ISU_CD', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode',
       'Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId'],
      dtype='object')

In [11]:
stocks_columns = ['Code', 'Name', 'Market', 'Dept','Close', 'ChangeCode','Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId']

In [12]:
stocks_desc_columns = ['Code', 'Sector', 'Industry', 'ListingDate','SettleMonth', 'Representative', 'HomePage', 'Region']

In [13]:
stocks = stocks[stocks_columns]

In [14]:
stocks_desc = stocks_desc[stocks_desc_columns]

In [15]:
import numpy as np
import pandas as pd

In [16]:
#stocks join stocks_desc
new_stocks = pd.merge(stocks,stocks_desc,on='Code')

In [17]:
new_stocks.shape

(2856, 23)

In [18]:
new_stocks.columns

Index(['Code', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode', 'Changes',
       'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount', 'Marcap',
       'Stocks', 'MarketId', 'Sector', 'Industry', 'ListingDate',
       'SettleMonth', 'Representative', 'HomePage', 'Region'],
      dtype='object')

In [19]:
new_stocks.head()

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,,53700,1,600,1.13,53200,54400,...,320577322935000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도
1,000660,SK하이닉스,KOSPI,,173000,1,5000,2.98,170000,175600,...,125944409145000,728002365,STK,반도체 제조업,"반도체,컴퓨터,통신기기 제조,도매",1996-12-26,12월,곽노정,http://www.skhynix.com,경기도
2,373220,LG에너지솔루션,KOSPI,,382000,2,-7000,-1.80,389000,395000,...,89388000000000,234000000,STK,일차전지 및 이차전지 제조업,"2차전지 (소형,ESS,자동차전지)",2022-01-27,12월,김동명,NaN,서울특별시
3,207940,삼성바이오로직스,KOSPI,,964000,1,3000,0.31,964000,981000,...,68611736000000,71174000,STK,기초 의약물질 제조업,바이오의약품,2016-11-10,12월,임존종보 (Rim John Chongbo),http://www.samsungbiologics.com,인천광역시
4,005380,현대차,KOSPI,,204500,2,-4500,-2.15,209000,210500,...,42825611059500,209416191,STK,자동차용 엔진 및 자동차 제조업,"자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업",1974-06-28,12월,"정의선, 장재훈, 이동석(각자 대표이사)",http://www.hyundai.com,서울특별시

In [20]:
# 엑셀로 저장하기
new_stocks.to_excel('stocks.xlsx',index=False)