FinanceData/FinanceDataReader: Financial data reader

In [40]:
# FinanceData 설치
# !pip install finance-datareader

In [41]:
# 라이브러리 불러오기
import FinanceDataReader as fdr

In [42]:
# 버전확인
fdr.__version__

'0.9.94'

#### 한국거래소 상장종목 전체 가져오기

In [43]:
# 패키지 내용 확인
dir(fdr)

['DataReader',
 'EtfListing',
 'SnapDataReader',
 'StockListing',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_utils',
 'chart',
 'data',
 'ecos',
 'fred',
 'investing',
 'krx',
 'nasdaq',
 'naver',
 'plot',
 'wikipedia',
 'yahoo']

In [44]:
# 함수, method 사용 방법을 알고 싶을때 함수,메소드명 뒤에 ?를 붙여 실행한다
# help(fdr.StockListing)
fdr.StockListing?

Signature: fdr.StockListing(market: str, start=None, end=None) -> pandas.core.frame.DataFrame
Docstring:
read stock list of stock exchanges
* market: 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP',
        'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC',
        'KRX-DELISTING', 'KRX-ADMINISTRATIVE', 'KRX-MARCAP',
        'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE',
        'S&P500',
        'ETF/KR',
File:      d:\kdt_2\anaconda3\lib\site-packages\financedatareader\data.py
Type:      function

In [45]:
stocks = fdr.StockListing('KRX')
stocks_desc = fdr.StockListing('KRX-DESC')

#### 데이터 구조 화인

In [46]:
# 데이터 프레임의 행과 열의 수를 튜플로 반환
stocks.shape, stocks_desc.shape

((2855, 17), (2855, 10))

In [47]:
#행수
stocks.shape[0] , stocks_desc.shape[0]

(2855, 2855)

In [48]:
# 데이터프레임의 처음,마지막 n행 보기, 매개값이 없여면 5행
display(stocks.head(1))
display(stocks_desc.head(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,54200,1,100,0.18,53500,54600,53300,12626235,680246198500,323562214210000,5969782550,STK

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,3S,KOSDAQ,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시

In [49]:
display(stocks.tail(1))
display(stocks_desc.tail(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
2854,419700,KR7419700000,이브이파킹서비스,KONEX,일반기업부,3,3,0,0.0,3,4,3,1261376,4572057,51799998,17266666,KNX

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
2854,238490,힘스,KOSDAQ,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [50]:
# 데이터 프레임에 대한 기본 정보(행수,컴럼명,컬럼수,각 컬럼의 데이터 타입, 결측치 확인)
stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2855 entries, 0 to 2854
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Code         2855 non-null   object
 1   ISU_CD       2855 non-null   object
 2   Name         2855 non-null   object
 3   Market       2855 non-null   object
 4   Dept         2855 non-null   object
 5   Close        2855 non-null   object
 6   ChangeCode   2855 non-null   object
 7   Changes      2855 non-null   int64
 8   ChagesRatio  2855 non-null   float64
 9   Open         2855 non-null   int64
 10  High         2855 non-null   int64
 11  Low          2855 non-null   int64
 12  Volume       2855 non-null   int64
 13  Amount       2855 non-null   int64
 14  Marcap       2855 non-null   int64
 15  Stocks       2855 non-null   int64
 16  MarketId     2855 non-null   object
dtypes: float64(1), int64(8), object(8)
memory usage: 379.3+ KB

In [51]:
# 요약 통계량 제공, 매개값이 없으면 숫자컬럼만 제공함.
# count : nan값을 제외한 컴럼 데이터수
# mean : 평균
# std : 표준편차
# min, max : 최소,최대값
# 사분위수 : 값의 범위를 4분위로 나눈 수. 
stocks.describe()

,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks
count,2855.000000,2855.000000,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03
mean,-589.654991,-3.129951,1.677611e+04,1.705802e+04,1.622482e+04,2.643048e+05,2.858076e+09,7.961094e+11,4.185993e+07
std,5754.753624,4.311956,5.537712e+04,5.692191e+04,5.096434e+04,1.138229e+06,1.865093e+10,7.271646e+12,1.328125e+08
min,-297000.000000,-29.920000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.180000e+07,2.000000e+05
25%,-450.000000,-5.350000,1.973500e+03,1.989500e+03,1.904500e+03,1.166400e+04,4.868690e+07,3.958202e+10,1.017186e+07
50%,-150.000000,-3.590000,4.450000e+03,4.550000e+03,4.305000e+03,4.680300e+04,2.133628e+08,8.710352e+10,1.976823e+07
75%,-33.000000,-1.500000,1.214000e+04,1.239500e+04,1.175500e+04,1.456250e+05,8.933890e+08,2.184063e+11,4.183980e+07
max,12500.000000,30.000000,1.845000e+06,1.930000e+06,1.500000e+06,2.967601e+07,6.802462e+11,3.235622e+14,5.969783e+09

In [52]:
# stocks['Marcap'].plot(kind='box')

In [53]:
# 문자열 컬럼(범주형 컬럼)에 대한 요약 통계보기
# count : 컬럼값의 수(nan값제외)
# unique : 컬럼의 고유값 갯수
# top : 최빈값(가장 빈번하게 나타나는 값) or 모든 컬럼 값이 유일한경우 제일 위에 위치한 값
# freq : 최빈값 빈도
stocks.describe(include='O')

          Code        ISU_CD  Name  Market  Dept Close ChangeCode MarketId
count     2855          2855  2855    2855  2855  2855       2855     2855
unique    2855          2855  2855       4    10  1968          6        3
top     005930  KR7005930003  삼성전자  KOSDAQ        2030          2      KSQ
freq         1             1     1    1728   959     7       2419     1776

In [54]:
# 고유값의 목록 확인
print(type(stocks['ChangeCode'].unique()))
print(stocks['ChangeCode'].unique())

<class 'numpy.ndarray'>
['1' '2' '0' '3' '5' '4']

In [55]:
# 고유값의 목록,갯수 확인
print(type(stocks['ChangeCode'].value_counts()))
print(stocks['ChangeCode'].value_counts())

<class 'pandas.core.series.Series'>
ChangeCode
2    2419
1     241
0     146
3      37
4       7
5       5
Name: count, dtype: int64

In [56]:
# 데이터 프레레임의 컬럼 메타정보
stocks.columns

Index(['Code', 'ISU_CD', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode',
       'Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId'],
      dtype='object')

In [57]:
# 데이터 프레레임의 인덱스 메타정보
stocks.index

RangeIndex(start=0, stop=2855, step=1)

In [58]:
# 컬럼제거 : 필요없는 행이나 열을 제거
new_stocks = stocks.drop('ISU_CD',axis=1)
new_stocks_desc = stocks_desc.drop(['Name', 'Market'],axis=1)
print(new_stocks.columns)
print(new_stocks_desc.columns)

Index(['Code', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode', 'Changes',
       'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount', 'Marcap',
       'Stocks', 'MarketId'],
      dtype='object')
Index(['Code', 'Sector', 'Industry', 'ListingDate', 'SettleMonth',
       'Representative', 'HomePage', 'Region'],
      dtype='object')

#### 2개의 데이터 프레임 합치기
- merge : 가로방향으로 열추가

In [59]:
import pandas as pd

In [ ]:
pd.merge?

In [61]:
# new_stocks join new_stocks_desc
new_stocks = pd.merge(new_stocks,new_stocks_desc,on='Code')

In [62]:
new_stocks.shape

(2855, 23)

In [63]:
new_stocks.head(1)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,,54200,1,100,0.18,53500,54600,...,323562214210000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

In [64]:
new_stocks_desc.head(1)

,Code,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시

#### 엑셀로 저장하기

In [65]:
# 엑셀로 저장하기
print(new_stocks.shape)
new_stocks.to_excel('stocks.xlsx',index=False)

(2855, 23)

In [66]:
df = pd.read_excel('stocks.xlsx')

In [67]:
df.shape

(2855, 23)

CSV파일로 저장하기

In [68]:
# CSV파일로 저장하기
new_stocks.to_csv('stocks.csv', index=False)

In [70]:
df = pd.read_csv('stocks.csv')

In [71]:
df.shape

(2855, 23)