FinanceData/FinanceDataReader: Financial data reader

In [47]:
# FinanceData 설치
# !pip install finance-datareader

In [48]:
# 라이브러리 불러오기
import FinanceDataReader as fdr

In [49]:
# 버전확인
fdr.__version__

'0.9.94'

#### 한국거래소 상장종목 전체 가져오기

In [50]:
# 패키지 내용 확인
dir(fdr)

['DataReader',
 'EtfListing',
 'SnapDataReader',
 'StockListing',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_utils',
 'chart',
 'data',
 'ecos',
 'fred',
 'investing',
 'krx',
 'nasdaq',
 'naver',
 'plot',
 'wikipedia',
 'yahoo']

In [51]:
# 함수, method 사용 방법을 알고 싶을때 함수,메소드명 뒤에 ?를 붙여 실행한다
# help(fdr.StockListing)
fdr.StockListing?

Signature: fdr.StockListing(market: str, start=None, end=None) -> pandas.core.frame.DataFrame
Docstring:
read stock list of stock exchanges
* market: 'KRX', 'KOSPI', 'KOSDAQ', 'KONEX', 'KRX-MARCAP',
        'KRX-DESC', 'KOSPI-DESC', 'KOSDAQ-DESC', 'KONEX-DESC',
        'KRX-DELISTING', 'KRX-ADMINISTRATIVE', 'KRX-MARCAP',
        'NASDAQ', 'NYSE', 'AMEX', 'SSE', 'SZSE', 'HKEX', 'TSE', 'HOSE',
        'S&P500',
        'ETF/KR',
File:      d:\kdt_2\anaconda3\lib\site-packages\financedatareader\data.py
Type:      function

In [52]:
stocks = fdr.StockListing('KRX')
stocks_desc = fdr.StockListing('KRX-DESC')

#### 데이터 구조 화인

In [53]:
# 데이터 프레임의 행과 열의 수를 튜플로 반환
stocks.shape, stocks_desc.shape

((2855, 17), (2855, 10))

In [54]:
#행수
stocks.shape[0] , stocks_desc.shape[0]

(2855, 2855)

In [55]:
# 데이터프레임의 처음,마지막 n행 보기, 매개값이 없여면 5행
display(stocks.head(1))
display(stocks_desc.head(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,54000,1,600,1.12,54500,54500,53700,16776565,906331224000,322368257700000,5969782550,STK

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,3S,KOSDAQ,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시

In [56]:
display(stocks.tail(1))
display(stocks_desc.tail(1))

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
2854,419700,KR7419700000,이브이파킹서비스,KONEX,일반기업부,2,3,0,0.0,3,3,2,3308954,7276237,34533332,17266666,KNX

,Code,Name,Market,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
2854,238490,힘스,KOSDAQ,특수 목적용 기계 제조업,"OLED Mask 인장기, OLED Mask 검사기 등",2017-07-20,12월,김주환,http://www.hims.co.kr,인천광역시

In [57]:
# 데이터 프레임에 대한 기본 정보(행수,컴럼명,컬럼수,각 컬럼의 데이터 타입, 결측치 확인)
stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2855 entries, 0 to 2854
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Code         2855 non-null   object
 1   ISU_CD       2855 non-null   object
 2   Name         2855 non-null   object
 3   Market       2855 non-null   object
 4   Dept         2855 non-null   object
 5   Close        2855 non-null   object
 6   ChangeCode   2855 non-null   object
 7   Changes      2855 non-null   int64
 8   ChagesRatio  2855 non-null   float64
 9   Open         2855 non-null   int64
 10  High         2855 non-null   int64
 11  Low          2855 non-null   int64
 12  Volume       2855 non-null   int64
 13  Amount       2855 non-null   int64
 14  Marcap       2855 non-null   int64
 15  Stocks       2855 non-null   int64
 16  MarketId     2855 non-null   object
dtypes: float64(1), int64(8), object(8)
memory usage: 379.3+ KB

In [58]:
# 요약 통계량 제공, 매개값이 없으면 숫자컬럼만 제공함.
# count : nan값을 제외한 컴럼 데이터수
# mean : 평균
# std : 표준편차
# min, max : 최소,최대값
# 사분위수 : 값의 범위를 4분위로 나눈 수. 
stocks.describe()

,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks
count,2855.000000,2855.000000,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03,2.855000e+03
mean,641.349212,4.534221,1.637270e+04,1.721863e+04,1.621827e+04,4.792033e+05,5.077584e+09,8.095303e+11,4.187273e+07
std,2349.693057,4.441277,5.152104e+04,5.457920e+04,5.053040e+04,2.338973e+06,2.793933e+10,7.268195e+12,1.328163e+08
min,-11000.000000,-14.980000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.453333e+07,2.000000e+05
25%,41.000000,1.760000,1.937500e+03,2.002500e+03,1.929500e+03,1.638000e+04,6.665265e+07,4.097112e+10,1.017186e+07
50%,180.000000,4.110000,4.340000e+03,4.630000e+03,4.300000e+03,6.727400e+04,3.059647e+08,9.084192e+10,1.976823e+07
75%,480.000000,6.630000,1.167000e+04,1.237000e+04,1.162500e+04,2.093645e+05,1.441645e+09,2.271988e+11,4.191386e+07
max,73000.000000,29.990000,1.511000e+06,1.664000e+06,1.446000e+06,4.864665e+07,9.063312e+11,3.223683e+14,5.969783e+09

In [59]:
# stocks[stocks['Name'] != '삼성전자']['Marcap'].plot(kind='box')

In [60]:
# 문자열 컬럼(범주형 컬럼)에 대한 요약 통계보기
# count : 컬럼값의 수(nan값제외)
# unique : 컬럼의 고유값 갯수
# top : 최빈값(가장 빈번하게 나타나는 값) or 모든 컬럼 값이 유일한경우 제일 위에 위치한 값
# freq : 최빈값 빈도
stocks.describe(include='O')

          Code        ISU_CD  Name  Market  Dept Close ChangeCode MarketId
count     2855          2855  2855    2855  2855  2855       2855     2855
unique    2855          2855  2855       4    10  1981          6        3
top     005930  KR7005930003  삼성전자  KOSDAQ        2080          1      KSQ
freq         1             1     1    1728   959    11       2474     1776

In [61]:
# 고유값의 목록 확인
print(type(stocks['ChangeCode'].unique()))
print(stocks['ChangeCode'].unique())

<class 'numpy.ndarray'>
['1' '2' '3' '0' '5' '4']

In [62]:
# 고유값의 목록,갯수 확인
print(type(stocks['ChangeCode'].value_counts()))
print(stocks['ChangeCode'].value_counts())

<class 'pandas.core.series.Series'>
ChangeCode
1    2474
2     171
0     136
3      50
4      19
5       5
Name: count, dtype: int64

In [63]:
# 데이터 프레레임의 컬럼 메타정보
stocks.columns

Index(['Code', 'ISU_CD', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode',
       'Changes', 'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount',
       'Marcap', 'Stocks', 'MarketId'],
      dtype='object')

In [64]:
# 데이터 프레레임의 인덱스 메타정보
stocks.index

RangeIndex(start=0, stop=2855, step=1)

In [65]:
# 컬럼제거 : 필요없는 행이나 열을 제거
new_stocks = stocks.drop('ISU_CD',axis=1)
new_stocks_desc = stocks_desc.drop(['Name', 'Market'],axis=1)
print(new_stocks.columns)
print(new_stocks_desc.columns)

Index(['Code', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode', 'Changes',
       'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount', 'Marcap',
       'Stocks', 'MarketId'],
      dtype='object')
Index(['Code', 'Sector', 'Industry', 'ListingDate', 'SettleMonth',
       'Representative', 'HomePage', 'Region'],
      dtype='object')

#### 2개의 데이터 프레임 합치기
- merge : 가로방향으로 열추가

In [66]:
import pandas as pd

In [67]:
pd.merge?

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.
on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.

    .. note::
        The `copy` keyword will change behavior in pandas 3.0.
        `Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        will be enabled by default, which means that all methods with a
        `copy` keyword will use a lazy copy mechanism to defer the copy and
        ignore the `copy` keyword. The `copy` keyword will be removed in a
        future version of pandas.

        You can already get the future behavior and improvements through
        enabling copy on write ``pd.options.mode.copy_on_write = True``
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  bar        2  bar        6
3  baz        3  baz        7
4  foo        5  foo        5
5  foo        5  foo        8

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      d:\kdt_2\anaconda3\lib\site-packages\pandas\core\reshape\merge.py
Type:      function

In [68]:
# new_stocks join new_stocks_desc
new_stocks = pd.merge(new_stocks,new_stocks_desc,on='Code')

In [69]:
new_stocks.shape

(2855, 23)

In [70]:
new_stocks.head(1)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,,54000,1,600,1.12,54500,54500,...,322368257700000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

In [71]:
new_stocks_desc.head(1)

,Code,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,060310,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",반도체 웨이퍼 캐리어,2002-04-23,03월,김세완,http://www.3sref.com,서울특별시

#### 엑셀로 저장하기

In [72]:
# 엑셀로 저장하기
print(new_stocks.shape)
new_stocks.to_excel('stocks.xlsx',index=False)

(2855, 23)

In [73]:
df = pd.read_excel('stocks.xlsx')

In [74]:
df.shape

(2855, 23)

CSV파일로 저장하기

In [75]:
# CSV파일로 저장하기
new_stocks.to_csv('stocks.csv', index=False)

In [76]:
df = pd.read_csv('stocks.csv')

In [77]:
df.shape

(2855, 23)

In [78]:
import numpy as np
df.select_dtypes(include='object').columns

Index(['Code', 'Name', 'Market', 'Dept', 'MarketId', 'Sector', 'Industry',
       'ListingDate', 'SettleMonth', 'Representative', 'HomePage', 'Region'],
      dtype='object')