In [65]:
import numpy as np
import pandas as pd

In [66]:
# 모든 컬럼을 출력하도록 설정
pd.set_option('display.max_columns', None)  # None으로 설정하면 모든 컬럼 출력

In [72]:
# 모든 행을 출력하도록 설정
pd.set_option('display.max_rows', None)  # None으로 설정하면 모든 행이 출력

In [73]:
# 출력 폭을 설정하여 긴 데이터 프레임도 잘리지 않도록 설정
pd.set_option('display.width', 1000)  # 원하는 폭으로 설정

In [74]:
df_stocks = pd.read_excel('stocks.xlsx')

In [75]:
df_stocks.shape

(2856, 23)

In [76]:
df_stocks.head(1)

     Code  Name Market Dept  Close  ChangeCode  Changes  ChagesRatio   Open   High    Low    Volume         Amount           Marcap      Stocks MarketId          Sector                                           Industry ListingDate SettleMonth Representative                    HomePage Region
0  005930  삼성전자  KOSPI  NaN  53700           1      600         1.13  53200  54400  53200  23588277  1270914173744  320577322935000  5969782550      STK  통신 및 방송 장비 제조업  통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...  1975-06-11         12월            한종희  http://www.samsung.com/sec    경기도

In [77]:
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2856 entries, 0 to 2855
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Code            2856 non-null   object
 1   Name            2856 non-null   object
 2   Market          2856 non-null   object
 3   Dept            1896 non-null   object
 4   Close           2856 non-null   int64
 5   ChangeCode      2856 non-null   int64
 6   Changes         2856 non-null   int64
 7   ChagesRatio     2856 non-null   float64
 8   Open            2856 non-null   int64
 9   High            2856 non-null   int64
 10  Low             2856 non-null   int64
 11  Volume          2856 non-null   int64
 12  Amount          2856 non-null   int64
 13  Marcap          2856 non-null   int64
 14  Stocks          2856 non-null   int64
 15  MarketId        2856 non-null   object
 16  Sector          2740 non-null   object
 17  Industry        2725 non-null   object
 18  ListingDate     2740 non-null   datetime64[ns]
 19  SettleMonth     2740 non-null   object
 20  Representative  2740 non-null   object
 21  HomePage        2548 non-null   object
 22  Region          2740 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(10), object(11)
memory usage: 513.3+ KB

In [78]:
df_stocks.describe()

             Close  ChangeCode    Changes  ChagesRatio         Open         High          Low        Volume               Amount                 Marcap           Stocks                    ListingDate
count     2,856.00    2,856.00   2,856.00     2,856.00     2,856.00     2,856.00     2,856.00      2,856.00             2,856.00               2,856.00         2,856.00                           2740
mean     17,529.67        1.73     -70.82        -1.13    17,430.18    17,811.27    16,980.58    445,260.49     5,502,098,957.64     818,468,009,312.01    41,879,673.73  2008-05-14 00:52:33.284671488
min           4.00        0.00 -34,500.00       -29.95         0.00         0.00         0.00          0.00                 0.00          69,066,664.00       200,000.00            1956-03-03 00:00:00
25%       2,078.75        1.00    -160.00        -2.58     2,015.00     2,035.00     1,990.75     14,928.25        62,410,915.00      41,892,808,203.75    10,173,538.00            2000-08-24 00:00:00
50%       4,900.00        2.00     -36.00        -1.03     4,787.50     4,850.00     4,635.00     60,789.00       286,379,418.50      91,391,476,625.00    19,781,204.50            2010-12-18 12:00:00
75%      12,952.50        2.00       0.00         0.00    12,935.00    13,140.00    12,480.00    201,175.50     1,365,354,745.00     229,631,214,023.75    41,964,315.00            2019-08-09 12:00:00
max   2,000,000.00        5.00 329,000.00        33.33 1,731,000.00 2,000,000.00 1,711,000.00 57,277,653.00 1,270,914,173,744.00 320,577,322,935,000.00 5,969,782,550.00            2024-11-29 00:00:00
std      58,047.36        0.63   6,341.05         3.78    55,363.07    58,957.08    54,351.67  2,279,376.63    35,160,666,255.00   7,266,422,282,073.96   132,789,599.62                            NaN

In [57]:
# 모든 숫자 컬럼에 대해 1000 단위 콤마 및 소수점 두 자리 표현 적용
def format_numbers(x):
    if isinstance(x, float):
        return f"{x:,.2f}"
    elif isinstance(x, int):
        return f"{x:,}"
    else:
        return x  # 숫자가 아닌 경우 그대로 반환

# 숫자 컬럼만 선택하여 포맷팅 적용
df_numeric = df_stocks.select_dtypes(include=['number'])  # 숫자 컬럼 선택
# display(df_numeric)
df_stocks[df_numeric.columns] = df_numeric.map(format_numbers)  # 포맷팅 적용

In [58]:
df_stocks

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,NaN,"53,700",1,600,1.13,"53,200","54,400",...,"320,577,322,935,000","5,969,782,550",STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도
1,000660,SK하이닉스,KOSPI,NaN,"173,000",1,"5,000",2.98,"170,000","175,600",...,"125,944,409,145,000","728,002,365",STK,반도체 제조업,"반도체,컴퓨터,통신기기 제조,도매",1996-12-26,12월,곽노정,http://www.skhynix.com,경기도
2,373220,LG에너지솔루션,KOSPI,NaN,"382,000",2,"-7,000",-1.80,"389,000","395,000",...,"89,388,000,000,000","234,000,000",STK,일차전지 및 이차전지 제조업,"2차전지 (소형,ESS,자동차전지)",2022-01-27,12월,김동명,NaN,서울특별시
3,207940,삼성바이오로직스,KOSPI,NaN,"964,000",1,"3,000",0.31,"964,000","981,000",...,"68,611,736,000,000","71,174,000",STK,기초 의약물질 제조업,바이오의약품,2016-11-10,12월,임존종보 (Rim John Chongbo),http://www.samsungbiologics.com,인천광역시
4,005380,현대차,KOSPI,NaN,"204,500",2,"-4,500",-2.15,"209,000","210,500",...,"42,825,611,059,500","209,416,191",STK,자동차용 엔진 및 자동차 제조업,"자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업",1974-06-28,12월,"정의선, 장재훈, 이동석(각자 대표이사)",http://www.hyundai.com,서울특별시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2851,245450,씨앤에스링크,KONEX,일반기업부,"1,400",1,100,7.69,"1,300","1,400",...,"2,211,944,000","1,579,960",KNX,통신 및 방송 장비 제조업,"내비게이션, LTE Router, 블랙박스",2016-06-24,12월,안상태,http://www.cns-link.co.kr,경기도
2852,288490,나라소프트,KONEX,일반기업부,57,2,-1,-1.72,58,58,...,"995,879,889","17,471,577",KNX,소프트웨어 개발 및 공급업,"체육용솔루션(NS트루골프, NS테니스, NS축구, NS승마 등)",2018-11-23,12월,김호상,http://www.narasoft.com,서울특별시
2853,308700,테크엔,KONEX,일반기업부,199,0,0,0.00,0,0,...,"796,000,000","4,000,000",KNX,전구 및 조명장치 제조업,LED조명장치,2018-12-21,12월,박철,http://www.techen.co.kr,대구광역시
2854,413300,티엘엔지니어링,KONEX,일반기업부,535,2,-5,-0.93,621,621,...,"698,450,525","1,305,515",KNX,"건축기술, 엔지니어링 및 관련 기술 서비스업",클린룸 설계 및 시공,2022-09-27,12월,서충옥,http://tleng.kr,경기도
2855,419700,이브이파킹서비스,KONEX,일반기업부,4,1,1,33.33,5,5,...,"69,066,664","17,266,666",KNX,기계장비 및 관련 물품 도매업,전기차 충전 솔루션 및 인프라,2023-07-05,12월,김정수,http://evps.co.kr/,서울특별시

In [59]:
df_stocks.columns

Index(['Code', 'Name', 'Market', 'Dept', 'Close', 'ChangeCode', 'Changes',
       'ChagesRatio', 'Open', 'High', 'Low', 'Volume', 'Amount', 'Marcap',
       'Stocks', 'MarketId', 'Sector', 'Industry', 'ListingDate',
       'SettleMonth', 'Representative', 'HomePage', 'Region'],
      dtype='object')

In [81]:
stocks_columns = {'Code':'종목코드', 'Name':'종목명', 'Market':'시장', 'Dept':'부서(한국거래소)', 'Close':'종가', 'ChangeCode':'등락기호','Changes':'전일대비', 
                     'ChagesRatio':'전일대비 등락률', 'Open':'시가','High':'고가', 'Low':'저가', 'Volume':'거래량', 'Amount':'거래대금', 'Marcap':'시가총액(백만원)', 
                     'Stocks':'주식발행수', 'MarketId':'시장기호', 'Sector':'업종', 'Industry':'산업', 'ListingDate':'상장일', 
                     'SettleMonth':'결산월', 'Representative':'대표자명','HomePage':'홈페이지', 'Region':'지역'}

In [84]:
# 컬럼명 변경
df_stocks.rename(columns = stocks_columns, inplace = True)

In [64]:
df_stocks

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,...,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,NaN,"53,700",1,600,1.13,"53,200","54,400",...,"320,577,322,935,000","5,969,782,550",STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도
1,000660,SK하이닉스,KOSPI,NaN,"173,000",1,"5,000",2.98,"170,000","175,600",...,"125,944,409,145,000","728,002,365",STK,반도체 제조업,"반도체,컴퓨터,통신기기 제조,도매",1996-12-26,12월,곽노정,http://www.skhynix.com,경기도
2,373220,LG에너지솔루션,KOSPI,NaN,"382,000",2,"-7,000",-1.80,"389,000","395,000",...,"89,388,000,000,000","234,000,000",STK,일차전지 및 이차전지 제조업,"2차전지 (소형,ESS,자동차전지)",2022-01-27,12월,김동명,NaN,서울특별시
3,207940,삼성바이오로직스,KOSPI,NaN,"964,000",1,"3,000",0.31,"964,000","981,000",...,"68,611,736,000,000","71,174,000",STK,기초 의약물질 제조업,바이오의약품,2016-11-10,12월,임존종보 (Rim John Chongbo),http://www.samsungbiologics.com,인천광역시
4,005380,현대차,KOSPI,NaN,"204,500",2,"-4,500",-2.15,"209,000","210,500",...,"42,825,611,059,500","209,416,191",STK,자동차용 엔진 및 자동차 제조업,"자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업",1974-06-28,12월,"정의선, 장재훈, 이동석(각자 대표이사)",http://www.hyundai.com,서울특별시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2851,245450,씨앤에스링크,KONEX,일반기업부,"1,400",1,100,7.69,"1,300","1,400",...,"2,211,944,000","1,579,960",KNX,통신 및 방송 장비 제조업,"내비게이션, LTE Router, 블랙박스",2016-06-24,12월,안상태,http://www.cns-link.co.kr,경기도
2852,288490,나라소프트,KONEX,일반기업부,57,2,-1,-1.72,58,58,...,"995,879,889","17,471,577",KNX,소프트웨어 개발 및 공급업,"체육용솔루션(NS트루골프, NS테니스, NS축구, NS승마 등)",2018-11-23,12월,김호상,http://www.narasoft.com,서울특별시
2853,308700,테크엔,KONEX,일반기업부,199,0,0,0.00,0,0,...,"796,000,000","4,000,000",KNX,전구 및 조명장치 제조업,LED조명장치,2018-12-21,12월,박철,http://www.techen.co.kr,대구광역시
2854,413300,티엘엔지니어링,KONEX,일반기업부,535,2,-5,-0.93,621,621,...,"698,450,525","1,305,515",KNX,"건축기술, 엔지니어링 및 관련 기술 서비스업",클린룸 설계 및 시공,2022-09-27,12월,서충옥,http://tleng.kr,경기도
2855,419700,이브이파킹서비스,KONEX,일반기업부,4,1,1,33.33,5,5,...,"69,066,664","17,266,666",KNX,기계장비 및 관련 물품 도매업,전기차 충전 솔루션 및 인프라,2023-07-05,12월,김정수,http://evps.co.kr/,서울특별시