In [15]:
# 데이터 분석 패키지
import numpy as np
import pandas as pd

In [16]:
# 모든 컬럼을 출력하도록 설정
pd.set_option('display.max_columns', None)  # None으로 설정하면 모든 컬럼 출력
# 모든 행을 출력하도록 설정
pd.set_option('display.max_rows', 50)  # None으로 설정하면 모든 행 출력

In [17]:
# 시각화 패키지
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
# matplotlib 한글지원 패키지
import koreanize_matplotlib

In [19]:
# 종목정보파일 데이터 프레임으로 가져오기
df_stocks = pd.read_csv('stocks.csv')

In [20]:
df_stocks.shape

(2855, 23)

In [21]:
df_stocks.head(1)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Sector,Industry,ListingDate,SettleMonth,Representative,HomePage,Region
0,005930,삼성전자,KOSPI,NaN,54200,1,100,0.18,53500,54600,53300,12626235,680246198500,323562214210000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

In [23]:
stocks_columns = {'Code':'종목코드', 'Name':'종목명', 'Market':'시장', 'Dept':'부서(한국거래소)', 'Close':'종가', 'ChangeCode':'등락기호','Changes':'전일대비', 
                     'ChagesRatio':'전일대비 등락률', 'Open':'시가','High':'고가', 'Low':'저가', 'Volume':'거래량', 'Amount':'거래대금', 'Marcap':'시가총액', 
                     'Stocks':'주식발행수', 'MarketId':'시장기호', 'Sector':'업종', 'Industry':'주요제품', 'ListingDate':'상장일', 
                     'SettleMonth':'결산월', 'Representative':'대표자명','HomePage':'홈페이지', 'Region':'지역'} 
# 컬럼명 변경
# inplace 매개변수 : 데이터프레임 원본을 수정하려면 True, 복사본을 반환받으려면 False
df_stocks.rename(columns = stocks_columns, inplace = True)

In [24]:
df_stocks.head(1)

,종목코드,종목명,시장,부서(한국거래소),종가,등락기호,전일대비,전일대비 등락률,시가,고가,저가,거래량,거래대금,시가총액,주식발행수,시장기호,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,005930,삼성전자,KOSPI,NaN,54200,1,100,0.18,53500,54600,53300,12626235,680246198500,323562214210000,5969782550,STK,통신 및 방송 장비 제조업,"통신 및 방송 장비 제조(무선) 제품, 반도체 제조(메모리) 제품, 전자부품 제조(...",1975-06-11,12월,한종희,http://www.samsung.com/sec,경기도

1. 서울 특별시 소재지를 두고 있는 KOSPI 종목의 종목명과 업종명 가져오기

In [25]:
df_stocks['지역'].unique()

array(['경기도', '서울특별시', '인천광역시', nan, '경상북도', '제주특별자치도', '울산광역시', '대전광역시',
       '전라남도', '경상남도', '충청북도', '세종특별자치시', '부산광역시', '충청남도', '강원특별자치도',
       '대구광역시', '전북특별자치도', '미국', '광주광역시', '싱가포르', '케이맨 제도', '홍콩', '일본'],
      dtype=object)

In [26]:
df_stocks['시장'].unique()

array(['KOSPI', 'KOSDAQ GLOBAL', 'KOSDAQ', 'KONEX'], dtype=object)

In [27]:
df_stocks['시장기호'].unique()

array(['STK', 'KSQ', 'KNX'], dtype=object)

In [ ]:
#case1)
cond1 = df_stocks['지역'] == '서울특별시'
cond2 = df_stocks['시장'] == 'KOSPI'
df_stocks[ cond1 & cond2 ]

#case2)
df_stocks[ (df_stocks['지역'] == '서울특별시') & (df_stocks['시장'] == 'KOSPI') ]

2. 2024년에 상장한 종목의 종목명,업종,시가총액,주식발행수 가져오기

In [38]:
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2855 entries, 0 to 2854
Data columns (total 23 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   종목코드       2855 non-null   object
 1   종목명        2855 non-null   object
 2   시장         2855 non-null   object
 3   부서(한국거래소)  1896 non-null   object
 4   종가         2855 non-null   int64
 5   등락기호       2855 non-null   int64
 6   전일대비       2855 non-null   int64
 7   전일대비 등락률   2855 non-null   float64
 8   시가         2855 non-null   int64
 9   고가         2855 non-null   int64
 10  저가         2855 non-null   int64
 11  거래량        2855 non-null   int64
 12  거래대금       2855 non-null   int64
 13  시가총액       2855 non-null   int64
 14  주식발행수      2855 non-null   int64
 15  시장기호       2855 non-null   object
 16  업종         2739 non-null   object
 17  주요제품       2724 non-null   object
 18  상장일        2739 non-null   object
 19  결산월        2739 non-null   object
 20  대표자명       2739 non-null   object
 21  홈페이지       2547 non-null   object
 22  지역         2739 non-null   object
dtypes: float64(1), int64(10), object(12)
memory usage: 513.1+ KB

In [ ]:
#case1) '-'를 구분자로하여 년도만 추출
day = '2024-12-09'
day.split('-')[0]

df_stocks['상장년도'] = df_stocks['상장일'].str.split('-').str[0]
df_stocks.head(2)

In [64]:
#case2) 문자열로 표현된 날짜를 날짜 타입으로 변경후 년도만 추출
# 문자열을 날짜 형식으로 변환
df_stocks['상장일'] = pd.to_datetime(df_stocks['상장일'])
# df_stocks['상장일'].dtype
df_stocks['상장년도2'] = df_stocks['상장일'].dt.year
# df_stocks['상장일'].dt.month
# df_stocks['상장일'].dt.day
df_stocks.head(1)
df_stocks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2855 entries, 0 to 2854
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   종목코드       2855 non-null   object
 1   종목명        2855 non-null   object
 2   시장         2855 non-null   object
 3   부서(한국거래소)  1896 non-null   object
 4   종가         2855 non-null   int64
 5   등락기호       2855 non-null   int64
 6   전일대비       2855 non-null   int64
 7   전일대비 등락률   2855 non-null   float64
 8   시가         2855 non-null   int64
 9   고가         2855 non-null   int64
 10  저가         2855 non-null   int64
 11  거래량        2855 non-null   int64
 12  거래대금       2855 non-null   int64
 13  시가총액       2855 non-null   int64
 14  주식발행수      2855 non-null   int64
 15  시장기호       2855 non-null   object
 16  업종         2739 non-null   object
 17  주요제품       2724 non-null   object
 18  상장일        2739 non-null   datetime64[ns]
 19  결산월        2739 non-null   object
 20  대표자명       2739 non-null   object
 21  홈페이지       2547 non-null   object
 22  지역         2739 non-null   object
 23  상장년도       2739 non-null   object
 24  상장년도2      2739 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(10), object(12)
memory usage: 557.7+ KB

In [71]:
len(df_stocks[df_stocks['상장년도'] == '2024'][['종목명','업종','시가총액','주식발행수']])
df_stocks[df_stocks['상장년도'] == '2024'][['종목명','업종','시가총액','주식발행수']].head(2)

          종목명                        업종           시가총액     주식발행수
61  HD현대마린솔루션  건축기술, 엔지니어링 및 관련 기술 서비스업  5591810000000  44450000
99       엘앤에프           일차전지 및 이차전지 제조업  3524374419800  36296338

In [ ]:
len(df_stocks[df_stocks['상장년도2'] == '2024'][['종목명','업종','시가총액','주식발행수']])
df_stocks[df_stocks['상장년도2'] == '2024'][['종목명','업종','시가총액','주식발행수']].head(2)